scrape_configs:
  - jobs_name: 'MTech applications input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:8000']
        labels:
          application: 'MTech applications'